[package]
name = "vite-embed-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
prod = ["dep:flate2"]
dev = []

[dependencies]
flate2 = { version = "1.0.25", optional = true }
mime_guess = "2.0.4"
quote = "1.0.23"
serde_json = "1.0.104"
